baseURL = 'https://ukvass.github.io/'
languageCode = 'en-us'
title = "Oleg's Webpage"
theme = 'PaperMod'

[params]
ShowReadingTime = true
ShowShareButtons = false
enableEmoji = true
defaultTheme = "auto"

  [params.homeInfoParams]
  Title = "Hello there! I'm Oleg.👋"
  Content = "Welcome to my webpage. For now, there is nothing here but my humble resume, but perhaps in the future this site will be filled with my projects."

  [[params.social]]
  name = "github"
  url = "https://github.com/ukvass"
