baseURL = 'https://ukvass.github.io/'
languageCode = 'en-us'
title = "Oleg's Webpage"
theme = 'PaperMod'

[Params]
ShowReadingTime = true
ShowShareButtons = true
defaultTheme = "auto"

[[socialIcons]]
name = "github"
url = "https://github.com/ukvass"

[[menu.main]]
identifier = "github"
name = "github"
url = "https://github.com/ukvass"
weight = 30