baseURL = 'https://ukvass.github.io/'
languageCode = 'en-us'
title = "Oleg's Webpage"
theme = 'PaperMod'

[Params]
ShowReadingTime = true
defaultTheme = "auto"

[[menu.main]]
socialIcons:
    - name = "github"
    - url = "https://github.com/ukvass"
